### ISSUE TITLE
Lighting issues on dm_2fort

### ISSUE THREAD

**Issue by occune** [KaidemonLP/open_fortress#17]
This issue can be reproduced with projectile weapons (like rocket launcher or grenade launcher)
https://www.youtube.com/watch?v=xeOhZnbsdhc
Position showed in video
setpos -528.827942 -1722.731323 -99.968681;setang 3.564032 -167.448685 0.000000

**Comment by KaidemonLP** [comment]
This is an inherent issue with dynamic lights. Static props get lit as a whole instead of their specific parts.
This is a engine level problem so there isnt a lot we can do about it.

**Comment by Nbc66** [comment]
Thats why we have **[info_light](https://developer.valvesoftware.com/wiki/Info_lighting)**  entity to specify where the lighting origin of the model should be

**Comment by KaidemonLP** [comment]
Still doesnt help with big props
