### ISSUE TITLE
Can't find servers

### ISSUE THREAD

**Issue by MrMeeseesks** [KaidemonLP/open_fortress#18]
I started the mod and wished to begin playing, but no servers are showing up at all. I try adding a server via favorites, but it doesn't show up at all. Any help?

**Comment by Chrissy573** [comment]
Our only server has been down for the entirety of the day, however it should be back up now. Make sure that you are not using any beta branches of the Source SDK Base 2013 Multiplayer tool and that your game folder is correctly named "open_fortress" (without the quotes).

**Comment by MrMeeseesks** [comment]
It was openfortress, not open_fortress. It works just fine now. Thanks for the tip!
